blueprint:
  homeassistant:
    min_version: "2024.10.0"
  name: 1 - Inovelli LED Color Change Test
  description:
    Create automations for Inovelli dimmers and switches to set their LED
    color. Specific to Z-Wave devices using Z-Wave JS and Zigbee devices using ZHA.
  domain: automation
  input:
    inovelli_dimmer:
      name: Inovelli Red Series Dimmer (LZW31-SN)
      description: List of available Inovelli Red Series dimmers (LZW31-SN).
      default: []
      selector:
        device:
          filter:
            - integration: zwave_js
              manufacturer: Inovelli
              model: LZW31-SN
            - integration: zwave_js
              manufacturer: Inovelli
              model: LZW31
          multiple: true
    inovelli_switch:
      name: Inovelli Red Series On/Off Switch (LZW30-SN)
      description: List of available Inovelli Red Series On/Off switches (LZW30-SN).
      default: []
      selector:
        device:
          filter:
            - integration: zwave_js
              manufacturer: Inovelli
              model: LZW30-SN
            - integration: zwave_js
              manufacturer: Inovelli
              model: LZW30
          multiple: true
    inovelli_fan_light_combo:
      name: Inovelli Res Series Fan/Light Combo (LZW36)
      description: List of available Inovelli fan/fight combo switches (LZW36).
      default: []
      selector:
        device:
          filter:
            - integration: zwave_js
              manufacturer: Inovelli
              model: LZW36
          multiple: true
    inovelli_red_2_in_1:
      name: Inovelli Red Series 2-in-1 Switch (VZW31-SN)
      description: List of available Inovelli Red Series 2-in-1 switches (VZW31-SN).
      default: []
      selector:
        device:
          filter:
            - integration: zwave_js
              manufacturer: Inovelli
              model: VZW31-SN
          multiple: true
    inovelli_blue_2_in_1:
      name: Inovelli Blue Series 2-in-1 Switch (VZM31-SN)
      description: List of available Inovelli Blue Series 2-in-1 switches (VZM31-SN).
      default: []
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: Inovelli
              model: VZM31-SN
          multiple: true
    color:
      name: Color
      description:
        "Select the LED Color - Off: 0 | Red: 1 | Orange: 21 | Yellow:
        42 | Green: 85 | Cyan: 127 | Teal: 145 | Blue: 170 | Purple: 195 | Light Pink:
        220 | Pink: 234 | White: 255"
      selector:
        number:
          min: 0.0
          max: 255.0
          mode: slider
          step: 1.0
  source_url: https://raw.githubusercontent.com/JDIacobbo/Home-Assistant/main/CONFIG/blueprints/automation/Inovelli_Set_LED_Color.yaml
variables:
  color: !input color
  inovelli_dimmer: !input inovelli_dimmer
  inovelli_switch: !input inovelli_switch
  inovelli_fan_light_combo: !input inovelli_fan_light_combo
  inovelli_red_2_in_1: !input inovelli_red_2_in_1
  inovelli_blue_2_in_1: !input inovelli_blue_2_in_1
trigger: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "True"
        sequence:
        - repeat:
            for_each:
              - inovelli_dimmer
            sequence:
              choose:
                - conditions: "{{ inovelli_dimmer|length > 0 }}"
                  sequence:
                    - action: zwave_js.multicast_set_value
                      data:
                        command_class: "112"
                        property: "13"
                        value: "{{ color }}"
                        device_id: !input inovelli_dimmer
        - repeat:
            for_each: 
              - inovelli_switch
            sequence: 
              choose:
                - conditions: "{{ inovelli_switch|length > 0 }}" 
                  sequence:
                    - action: zwave_js.multicast_set_value
                      data:
                        command_class: "112"
                        property: "5"
                        value: "{{ color }}"
                        device_id: !input inovelli_switch
        - repeat:
            for_each: 
              - inovelli_fan_light_combo
            sequence: 
              choose:
                - conditions: "{{ inovelli_fan_light_combo|length > 0 }}" 
                  sequence: 
                    - action: zwave_js.multicast_set_value
                      data:
                        command_class: "112"
                        property: "18"
                        value: "{{ color }}"
                        device_id: !input inovelli_fan_light_combo
                    - action: zwave_js.multicast_set_value
                      data:
                        command_class: "112"
                        property: "20"
                        value: "{{ color }}"
                        device_id: !input inovelli_fan_light_combo
        - repeat:
            for_each: 
              - inovelli_red_2_in_1
            sequence:
              choose:
                - conditions: "{{ inovelli_red_2_in_1|length > 0 }}" 
                  sequence: 
                    - action: zwave_js.multicast_set_value
                      data:
                        command_class: "112"
                        property: "95"
                        value: "{{ color }}"
                        device_id: !input inovelli_red_2_in_1
                    - action: zwave_js.multicast_set_value
                      data:
                        command_class: "112"
                        property: "96"
                        value: "{{ color }}"
                        device_id: !input inovelli_red_2_in_1
        - repeat:
            for_each: "{{ inovelli_blue_2_in_1 }}"
            sequence:  
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 96
                  manufacturer: "4655"
                  ieee: '{{ (device_attr(repeat.item, "identifiers")|list).0.1 }}'
                  value: "{{ color }}"
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 95
                  manufacturer: "4655"
                  ieee: '{{ (device_attr(repeat.item, "identifiers")|list).0.1 }}'
                  value: "{{ color }}"
              # Reset default color for Blue 2-in-1 off
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 61
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 66
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 71
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 76
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 81
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 86
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 91
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              # Reset default color for Blue 2-in-1 on
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 60
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 65
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 70
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 75
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 80
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 85
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
              - action: zha.set_zigbee_cluster_attribute
                data:
                  cluster_type: in
                  endpoint_id: 1
                  cluster_id: 64561
                  attribute: 90
                  manufacturer: "4655"
                  ieee: >
                    {{ (device_attr(repeat.item, "identifiers")|list).0.1 }}
                  value: 255
